
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mata?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: create
  data:
    cassandra:
      contact-points: 172.16.238.2:9042
      keyspace-name: mykeyspace