
server:
  port: 8080

logging:
  level:
    web: info
    sql: info
springdoc:
  use-fqn: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mata?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
      password: ssafy8a506
    cassandra:
      contact-points: 172.16.238.2:9042
      keyspace-name: mykeyspace
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://metastore:3306/mata?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379
      password: ssafy8a506
    cassandra:
      contact-points: 172.16.238.2:9042
      keyspace-name: mykeyspace
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN