spring:
  config:
    activate:
      on-profile: dev
#  hive:
#    driver-class-name: org.apache.hive.jdbc.HiveDriver
#    url: jdbc:hive2://master01:10000/test
#    username: hive
#    password: hive